// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Up2Ai.Data;

#nullable disable

namespace Up2Ai.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917052607_PostgresLeadStorage")]
    partial class PostgresLeadStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Up2Ai.Data.LeadEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("Business")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text")
                        .HasColumnName("internal_notes");

                    b.Property<DateTimeOffset?>("LastContactedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_contacted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Need")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("need");

                    b.Property<string>("Reach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reach");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("new")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("leads", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
